name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches: [main]
    paths-ignore:
      - '.github/**'
      - '*.md'

jobs:
  tests:
    name: CodeQL Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
        run: |
          echo "running unit test..."
          echo "unit tests passed!"

  codeql-analysis:
    permissions:
      actions: read
      contents: read
      security-events: write
    name: CodeQL Scan
    uses: ./.github/workflows/security_codeql.yml

  semgrep-analysis:
    permissions:
      security-events: write
    name: Semgrep Scan
    uses: ./.github/workflows/security_semgrep.yml
  
  dast-scan:
    permissions:
      security-events: write
    name: Dastardly
    uses: ./.github\workflows\security_dastardly.yml
