name: Dependency Scan
on:
  workflow_call:

jobs:
  SCA:
    permissions:
      security-events: write
    name: Dependency Scanning
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
